# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Redline < Formula
  desc "Budget-aware dispatcher that spends spare Codex and Claude subscription quota on queued agent jobs"
  homepage "https://github.com/croutoncreations/redline"
  version "0.1.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/croutoncreations/redline/releases/download/v0.1.7/redline_0.1.7_darwin_amd64.tar.gz"
      sha256 "6dcca06e86a2a67ebbc028584f88d90a47b2794c801e04dff3d5f0c2d9f21239"

      define_method(:install) do
        bin.install "redline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/croutoncreations/redline/releases/download/v0.1.7/redline_0.1.7_darwin_arm64.tar.gz"
      sha256 "624fa2d154729e23f90c7e59e0028b0eb63eea9ba8279d22b922f7877033e101"

      define_method(:install) do
        bin.install "redline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/croutoncreations/redline/releases/download/v0.1.7/redline_0.1.7_linux_amd64.tar.gz"
      sha256 "e5039d1d8650dc8fca7c250e1a6e4574d4df6563f6b8e7bef81d4aa9f24dd61c"
      define_method(:install) do
        bin.install "redline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/croutoncreations/redline/releases/download/v0.1.7/redline_0.1.7_linux_arm64.tar.gz"
      sha256 "b30ef94af1a3deca712bbce148a1a011da175df84791fc274edbf85423442f50"
      define_method(:install) do
        bin.install "redline"
      end
    end
  end

  def caveats
    <<~EOS
      The CLI is also bundled inside Redline.app. If you use the menu-bar app,
      you do not need this formula; the app's copy lives at
      /Applications/Redline.app/Contents/Resources/bin/redline.

      For the app itself:  brew install --cask croutoncreations/tap/redline
    EOS
  end

  test do
    assert_match "redline #{version}", shell_output("#{bin}/redline version")
  end
end
