# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Redline < Formula
  desc "Budget-aware dispatcher that spends spare Codex and Claude subscription quota on queued agent jobs"
  homepage "https://github.com/croutoncreations/redline"
  version "0.1.7-rc.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/croutoncreations/redline/releases/download/v0.1.7-rc.1/redline_0.1.7-rc.1_darwin_amd64.tar.gz"
      sha256 "4faf7587ac535887ea370c2380dca1a392f6daa78e130ad7fbf5f3174edb9a0d"

      define_method(:install) do
        bin.install "redline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/croutoncreations/redline/releases/download/v0.1.7-rc.1/redline_0.1.7-rc.1_darwin_arm64.tar.gz"
      sha256 "e9db4ff196af9b56c9f7de7750fae42729fea50904c888c3361f59a9c475bf79"

      define_method(:install) do
        bin.install "redline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/croutoncreations/redline/releases/download/v0.1.7-rc.1/redline_0.1.7-rc.1_linux_amd64.tar.gz"
      sha256 "25b794f4fb2c5a40f7bcc0faf0473bd9c9b578a4bcc3b95791a234cf7cf85a01"
      define_method(:install) do
        bin.install "redline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/croutoncreations/redline/releases/download/v0.1.7-rc.1/redline_0.1.7-rc.1_linux_arm64.tar.gz"
      sha256 "682f8f2cabf2bb2a8bb1c42ca11c7ece922344be54b8e964ba2c1681404b0cac"
      define_method(:install) do
        bin.install "redline"
      end
    end
  end

  def caveats
    <<~EOS
      The CLI is also bundled inside Redline.app. If you use the menu-bar app,
      you do not need this formula; the app's copy lives at
      /Applications/Redline.app/Contents/Resources/bin/redline.

      For the app itself:  brew install --cask croutoncreations/tap/redline
    EOS
  end

  test do
    assert_match "redline #{version}", shell_output("#{bin}/redline version")
  end
end
